services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      # Laravel/PHPUnit/Pest environment variables
      APP_ENV: testing
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
    command: composer test

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
